---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: catalina-box
    driver:
      box: catalina-box
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default
