Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "catalina-box"
  c.vm.hostname = "default-catalina-box.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-vagrant-default-catalina-box-f2d768b3-4586-4b79-b30a-227aafb21fd8"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
