Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "xenial64"
  c.vm.hostname = "default-vbox-xenial64.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.name = "kitchen-vagrant-default-vbox-xenial64-1b36bc22-9f08-4e69-b0b1-f33716e307de"
    p.customize ["modifyvm", :id, "--audio", "none"]
  end
end
